### ISSUE TITLE
Protected property problem

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/swup-livewire-plugin#1]
Hey, great work on this. It's so much easier than having to custom swup code to each project.

Anyway... I have this problem and I don't understand it, but perhaps somebody else will run into the same problem eventually.

In Livewire sometimes you get this error: **Livewire encountered corrupt data when trying to hydrate...**

It usually happens when I pass data to the livewire component like so:

```
**page.blade.php**
@livewire('location-search', ['selectedLocation ' => $location])
```

And in my component:

```

protected $selectedLocation;

public function mount($selectedLocation = null)
{
  $this->selectedLocation = $selectedLocation;
}

public function render()
{
   return view('livewire.location-search', [
      'selectedLocation' => $this->selectedLocation,
   ]);
}

```

This seems to be a commonly used solution to the error above, and it works fine when not using Swup. Once I introduce swup then the $selectedLocation gets lost after the livewire refresh.

Somehow I need to maintain the $selectedLocation after a swup refresh, or else come up with a better solution that doesn't use protected properties.

**Comment by stuartcusackie** [comment]
Solved it. This post explains it:
https://forum.laravel-livewire.com/t/protected-private-properties-missing/1227/2

**Comment by aerni** [comment]
Yeah, this is a common issue. I use the `hydrate` method for this, which is called right after `mount`. Check the [Lifecycle Hooks documentation](https://laravel-livewire.com/docs/2.x/lifecycle-hooks).

Here's the example from the link above but with `hydrate`:

```php
class Profile extends Component
{
  public $user_id
  protected $user;

  public function mount(User $user)
  {
    $this->user_id = $user->id;
    $this->user = $user;
  }

  public function hydrate()
  {
    if (!$this->user) $this->user = User::findOrFail($this->user_id);
  }

  public function render()
  {
    return view('users.profile)->with('user, $this->user);
  }
```

**Comment by stuartcusackie** [comment]
Thanks for this. I know it's not really a problem with your plugin.
